#pragma once
static const Engine_Object map[] = {
	{
		.visual.transform.scale.x = 512.0,
		.visual.transform.scale.y = 512.0,
		.visual.transform.scale.z = 512.0,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 0.0,
		.visual.transform.translation.y = 0.0,
		.visual.transform.translation.z = 0.0,
		.visual.transform.translation.w = 512,
		.visual.transform.rotation.x = 0.0,
		.visual.transform.rotation.y = 0.0,
		.visual.transform.rotation.z = 0.0,
		.visual.transform.rotation.w = 512,
		.visual.config.backfaceCulling = 2,
		.visual.solid_color = 204,
		.visual.config.visible = 2,
		.visual.model = &interior_desk_with_computer,
		.visual_type = 2,
		.view_range = 131072,
		.collisions = 0,
		.process = 0,
		.data = 0,
	},
	{
		.visual.transform.scale.x = 512.0,
		.visual.transform.scale.y = 512.0,
		.visual.transform.scale.z = 512.0,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 387.79815673828125,
		.visual.transform.translation.y = 0,
		.visual.transform.translation.z = -86.99427795410156,
		.visual.transform.translation.w = 512,
		.visual.transform.rotation.x = 0.0,
		.visual.transform.rotation.y = -163.49723858880662,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = 512,
		.visual.config.backfaceCulling = 2,
		.visual.solid_color = 204,
		.visual.config.visible = 2,
		.visual.model = &interior_office_chair,
		.visual_type = 2,
		.view_range = 131072,
		.collisions = 0,
		.process = 0,
		.data = 0,
	},
};
