#pragma once
static const Engine_Object map[] = {
	{
		.visual.transform.scale.x = 512.0,
		.visual.transform.scale.y = 512.0,
		.visual.transform.scale.z = 512.0,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 38400.0,
		.visual.transform.translation.y = 1024.0,
		.visual.transform.translation.z = 5120.0,
		.visual.transform.translation.w = 512,
		.visual.transform.rotation.x = 0.0,
		.visual.transform.rotation.y = 0.0,
		.visual.transform.rotation.z = 0.0,
		.visual.transform.rotation.w = 512,
		.visual.config.backfaceCulling = 2,
		.visual.solid_color = 204,
		.visual.config.visible = 2,
		.visual.model = &local_level_generic_building_0,
		.visual_type = 2,
		.view_range = 131072,
		.collisions = 0,
		.process = 0,
		.data = 0,
	},
	{
		.visual.transform.scale.x = 512.0,
		.visual.transform.scale.y = 512.0,
		.visual.transform.scale.z = 512.0,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = -25259.0625,
		.visual.transform.translation.y = 0.0,
		.visual.transform.translation.z = 0.0,
		.visual.transform.translation.w = 512,
		.visual.transform.rotation.x = 0.0,
		.visual.transform.rotation.y = 0.0,
		.visual.transform.rotation.z = 0.0,
		.visual.transform.rotation.w = 512,
		.visual.config.backfaceCulling = 2,
		.visual.solid_color = 204,
		.visual.config.visible = 2,
		.visual.model = &local_level_launch_tower_0,
		.visual_type = 2,
		.view_range = 131072,
		.collisions = 0,
		.process = 0,
		.data = 0,
	},
	// {
	// 	.visual.transform.scale.x = 20480.0,
	// 	.visual.transform.scale.y = 512.0,
	// 	.visual.transform.scale.z = 102400.0,
	// 	.visual.transform.scale.w = 0,
	// 	.visual.transform.translation.x = 102400.0,
	// 	.visual.transform.translation.y = 0.0,
	// 	.visual.transform.translation.z = 0.0,
	// 	.visual.transform.translation.w = 512,
	// 	.visual.transform.rotation.x = 0.0,
	// 	.visual.transform.rotation.y = 0.0,
	// 	.visual.transform.rotation.z = 0.0,
	// 	.visual.transform.rotation.w = 512,
	// 	.visual.config.backfaceCulling = 1,
	// 	.visual.solid_color = 128,
	// 	.visual.config.visible = 8,
	// 	.visual.model = &Plane,
	// 	.visual_type = 2,
	// 	.view_range = 131072,
	// 	.collisions = 0,
	// 	.process = 0,
	// 	.data = 0,
	// },
	{
		.visual.transform.scale.x = 512.0,
		.visual.transform.scale.y = 512.0,
		.visual.transform.scale.z = 512.0,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = -24717.009765625,
		.visual.transform.translation.y = 785.0348510742188,
		.visual.transform.translation.z = 0.0,
		.visual.transform.translation.w = 512,
		.visual.transform.rotation.x = 0.0,
		.visual.transform.rotation.y = 128.0000035619245,
		.visual.transform.rotation.z = -0.0,
		.visual.transform.rotation.w = 512,
		.visual.config.backfaceCulling = 2,
		.visual.solid_color = 204,
		.visual.config.visible = 2,
		.visual.model = &local_level_rocket_0,
		.visual_type = 2,
		.view_range = 131072,
		.collisions = 0,
		.process = 0,
		.data = 0,
	},
	// {
	// 	.visual.transform.scale.x = 51200.0,
	// 	.visual.transform.scale.y = 512.0,
	// 	.visual.transform.scale.z = 51200.0,
	// 	.visual.transform.scale.w = 0,
	// 	.visual.transform.translation.x = 0.0,
	// 	.visual.transform.translation.y = 0.0,
	// 	.visual.transform.translation.z = 0.0,
	// 	.visual.transform.translation.w = 512,
	// 	.visual.transform.rotation.x = 0.0,
	// 	.visual.transform.rotation.y = 0.0,
	// 	.visual.transform.rotation.z = 0.0,
	// 	.visual.transform.rotation.w = 512,
	// 	.visual.config.backfaceCulling = 1,
	// 	.visual.solid_color = 128,
	// 	.visual.config.visible = 8,
	// 	.visual.model = &local_level_rocket_scene_terrain,
	// 	.visual_type = 2,
	// 	.view_range = 131072,
	// 	.collisions = 0,
	// 	.process = 0,
	// 	.data = 0,
	// },
};
